### ISSUE TITLE
NameError: name 'args' is not defined

### ISSUE THREAD

**Issue by falsetry1514** [rajewsky-lab/spacemake#122]
When the program runs the job of creating the file--puck_count_prealigned_barcode_matches.csv , it reports an Error.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/server3/miniforge3/envs/spacemake/lib/python3.10/site-packages/spacemake/snakemake/scripts/n_intersect_sequences.py", line 305, in <module>
    cmdline()
  File "/Users/server3/miniforge3/envs/spacemake/lib/python3.10/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/Users/server3/miniforge3/envs/spacemake/lib/python3.10/site-packages/spacemake/snakemake/scripts/n_intersect_sequences.py", line 292, in cmdline
    results = pool.map(find_matches, args.target)
  File "/Users/server3/miniforge3/envs/spacemake/lib/python3.10/multiprocessing/pool.py", line 367, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/Users/server3/miniforge3/envs/spacemake/lib/python3.10/multiprocessing/pool.py", line 774, in get
    raise self._value
  File "/Users/server3/miniforge3/envs/spacemake/lib/python3.10/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/Users/server3/miniforge3/envs/spacemake/lib/python3.10/multiprocessing/pool.py", line 48, in mapstar
    return list(map(*args))
  File "/Users/server3/miniforge3/envs/spacemake/lib/python3.10/site-packages/spacemake/snakemake/scripts/n_intersect_sequences.py", line 242, in find_matches
    args.target_tag,
NameError: name 'args' is not defined.

I have a look at n_intersect_sequences.py, it seems that args = parser.parse_args() don't work?

**Comment by falsetry1514** [comment]
I tried to run this step 'merge_stats_prealigned_spatial_barcodes' by this py file, but also the multiprocessing.pool function return an error:
with mp.Pool(args.n_jobs) as pool:
        results = pool.map(find_matches, args.target)
AttributeError: Can't get attribute 'find_matches' on <module '__main__' (built-in)>
I searched solution for this error, and found the problem due to the 'with' statement:
This is cited by the site https://stackoverflow.com/questions/41385708/multiprocessing-example-giving-attributeerror.
It seems that the multiprocessing module doesn't work correctly in this situation.

**Comment by falsetry1514** [comment]
I successfully ran the py file by replacing multiprocessing module with multiprocess module, the latter module looks more versatile
