### ISSUE TITLE
restore cmd line functionality for adding barcode_flavor

### ISSUE THREAD

**Issue by nukappa** [rajewsky-lab/spacemake#39]
Functionality is currently broken on the master branch.

```
spacemake config add_barcode_flavor
usage: spacemake config add_barcode_flavor [-h] --name NAME --umi UMI --cell_barcode CELL_BARCODE
spacemake config add_barcode_flavor: error: the following arguments are required: --name, --umi, --cell_barcode
```

Giving name, umi and cell_barcode does not work:

```
spacemake config add_barcode_flavor --name fc_sts_miniseq --umi r2[0:9] --cell_barcode r1[2:27]
add_variable() called with variable=barcode_flavors name=fc_sts_miniseq kw={'umi': 'r2[0:9]', 'cell_barcode': 'r1[2:27]', 'name': 'fc_sts_miniseq'}
Traceback (most recent call last):
  File "../miniconda3/envs/smk/bin/spacemake", line 8, in <module>
    sys.exit(cmdline())
  File "../miniconda3/envs/smk/lib/python3.10/site-packages/spacemake/smk.py", line 604, in cmdline
    func(args)
  File "../miniconda3/envs/smk/lib/python3.10/site-packages/spacemake/config.py", line 261, in <lambda>
    func = lambda args: add_update_delete_variable_cmdline(config, args)
  File "../miniconda3/envs/smk/lib/python3.10/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "../miniconda3/envs/smk/lib/python3.10/site-packages/spacemake/config.py", line 331, in add_update_delete_variable_cmdline
    var_variables = func(variable, name, **args)
  File "../miniconda3/envs/smk/lib/python3.10/site-packages/spacemake/config.py", line 745, in add_variable
    values = self.process_variable_args(variable, **kwargs)
  File "../miniconda3/envs/smk/lib/python3.10/site-packages/spacemake/config.py", line 710, in process_variable_args
    return self.process_barcode_flavor_args(**kwargs)
TypeError: ConfigFile.process_barcode_flavor_args() got an unexpected keyword argument 'name'
```

**Comment by marvin-jens** [comment]
fixed by drop-dropseq commit b39180 . Also added unittests for add/update/delete of barcode_flavor, adapter, and adapter_flavor
