### ISSUE TITLE
Error when adding the --download_species during init

### ISSUE THREAD

**Issue by nukappa** [rajewsky-lab/spacemake#70]
Starting with a fresh installation (v0.7.2), adding the `--download_species` during initialization

`spacemake init --download_species human --dropseq_tools /Drop-seq_tools-2.5.1/`

throws an error:

```
usage: spacemake [-h] [--version] {init} ...
spacemake: error: unrecognized arguments: human
```

**Comment by nukappa** [comment]
Never mind, it doesn't need species ref `human` and by default downloads human + mouse

**Comment by nukappa** [comment]
The DGA actually runs all the way but then throws the following:

```
Complete log:/.snakemake/log/2023-07-17T093207.614063.snakemake.log
Traceback (most recent call last):
  File "/miniconda3/envs/spacemake/bin/spacemake", line 8, in <module>
    sys.exit(cmdline())
  File "/miniconda3/envs/spacemake/lib/python3.10/site-packages/spacemake/smk.py", line 613, in cmdline
    func(args)
  File "/miniconda3/envs/spacemake/lib/python3.10/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/miniconda3/envs/spacemake/lib/python3.10/site-packages/spacemake/smk.py", line 340, in spacemake_init
    cf.add_variable(
  File "/miniconda3/envs/spacemake/lib/python3.10/site-packages/spacemake/config.py", line 752, in add_variable
    values = self.process_variable_args(variable, **kwargs)
  File "/miniconda3/envs/spacemake/lib/python3.10/site-packages/spacemake/config.py", line 728, in process_variable_args
    return self.process_species_args(**kwargs)
TypeError: ConfigFile.process_species_args() got an unexpected keyword argument 'genome'
```

**Comment by marvin-jens** [comment]
Just tested `spacemake init --download_species --dropseq_tools /data/rajewsky/shared_bins/Drop-seq_tools-2.5.1/` with a fresh pull from master and it ran without errors. If you can confirm Nikos, I think we can close this one.

**Comment by nukappa** [comment]
Indeed current master version (0.7.3) runs fine
